
CREATE RANDOM STREAM r_products                                                 
(                                                                               
    `id` string DEFAULT 'key_' || to_string(rand64() % 300000000),                          
    `name` string,                                                              
    `d1` string,                                                                
    `d2` string,                                                                
    `d3` string,                                                                
    `d4` string,                                                                
    `d5` string,                                                                
    `d6` string,                                                                
    `d7` string,                                                                
    `d8` string,                                                                
    `d9` string,                                                                
    `d10` string,                                                               
    `d11` string,                                                               
    `d12` string,                                                               
    `d13` string,                                                               
    `d14` string,                                                               
    `d15` string,                                                               
    `d16` string,                                                               
    `d17` string,                                                               
    `d18` string,                                                               
    `d19` string,                                                               
    `d20` string,                                                               
    `d21` string,                                                               
    `d22` string,                                                               
    `d23` string,                                                               
    `d24` string,                                                               
    `d25` string,                                                               
    `d26` string,                                                               
    `d27` string,                                                               
    `d28` string,                                                               
    `d29` string,                                                               
    `d30` string,                                                               
    `d31` string,                                                               
    `d32` string,                                                               
    `d33` string,                                                               
    `d34` string,                                                               
    `d35` string,                                                               
    `d36` string,                                                               
    `d37` string,                                                               
    `d39` string,                                                               
    `d40` string,                                                               
    `d41` string,                                                               
    `d42` string,                                                               
    `d43` string,                                                               
    `d44` string,                                                               
    `d45` string,                                                               
    `d46` string,                                                               
    `d47` string,                                                               
    `d48` string,                                                               
    `d49` string,                                                               
    `d50` string,                                                               
    `dt` datetime64(3)                                                          
) SETTINGS shards=8; 

create mutable stream products                                                 
(                                                                               
    `id` string,                          
    `name` string,                                                              
    `d1` string,                                                                
    `d2` string,                                                                
    `d3` string,                                                                
    `d4` string,                                                                
    `d5` string,                                                                
    `d6` string,                                                                
    `d7` string,                                                                
    `d8` string,                                                                
    `d9` string,                                                                
    `d10` string,                                                               
    `d11` string,                                                               
    `d12` string,                                                               
    `d13` string,                                                               
    `d14` string,                                                               
    `d15` string,                                                               
    `d16` string,                                                               
    `d17` string,                                                               
    `d18` string,                                                               
    `d19` string,                                                               
    `d20` string,                                                               
    `d21` string,                                                               
    `d22` string,                                                               
    `d23` string,                                                               
    `d24` string,                                                               
    `d25` string,                                                               
    `d26` string,                                                               
    `d27` string,                                                               
    `d28` string,                                                               
    `d29` string,                                                               
    `d30` string,                                                               
    `d31` string,                                                               
    `d32` string,                                                               
    `d33` string,                                                               
    `d34` string,                                                               
    `d35` string,                                                               
    `d36` string,                                                               
    `d37` string,                                                               
    `d39` string,                                                               
    `d40` string,                                                               
    `d41` string,                                                               
    `d42` string,                                                               
    `d43` string,                                                               
    `d44` string,                                                               
    `d45` string,                                                               
    `d46` string,                                                               
    `d47` string,                                                               
    `d48` string,                                                               
    `d49` string,                                                               
    `d50` string,                                                               
    `dt` DateTime64(3)                                                         
) PRIMARY KEY id
SETTINGS shards = 8;


-- Populate ~200 million products
INSERT INTO products(* EXCEPT(_tp_sn)) SELECT * FROM r_products LIMIT 200000000 SETTINGS eps = 10000000;
