#!/usr/bin/env python3
"""
produce.py — produce PLAIN protobuf Event messages to a Kafka topic.

Each Kafka message value is a raw `Event.SerializeToString()` — NO Confluent
wire framing (no magic byte / schema id / message-index). This is what Proton's
native ProtobufSingle format expects. Timeplus decodes it in C++ using the
CREATE FORMAT SCHEMA registered in timeplus_streams.sql; the Python router only
routes the decoded columns.

Usage:
  pip install confluent-kafka protobuf grpcio-tools
  ./setup.sh                      # generates event_pb2.py + creates the topic
  python produce.py [--broker localhost:9092] [--topic events-envelope] [--count 10]
"""

import argparse
import random
import time
import uuid

from confluent_kafka import Producer

# Generated by setup.sh (python -m grpc_tools.protoc ...)
import event_pb2


def _order() -> event_pb2.Event:
    return event_pb2.Event(
        event_type  = "order",
        order_id    = str(uuid.uuid4()),
        amount      = round(random.uniform(1.0, 999.99), 2),   # > 500 => tier "hot"
        customer_id = f"cust-{random.randint(1000, 9999)}",
    )


def _device() -> event_pb2.Event:
    return event_pb2.Event(
        event_type  = "device",
        device_id   = f"dev-{random.randint(1, 50):03d}",
        temperature = round(random.uniform(20.0, 100.0), 1),   # > 80 => status "alert"
    )


def _click() -> event_pb2.Event:
    agents = ["Mozilla/5.0", "Safari/17.0", "Chrome/124.0", "Googlebot/2.1"]
    return event_pb2.Event(
        event_type = "click",
        session_id = str(uuid.uuid4()),
        url        = random.choice(["/home", "/cart", "/checkout", "/product/42"]),
        user_agent = random.choice(agents),                    # ~1/4 bot => dropped
    )


GENERATORS = [_order, _device, _click]


def main():
    parser = argparse.ArgumentParser(description="Produce plain Protobuf Event messages")
    parser.add_argument("--broker", default="localhost:9092",  help="Kafka broker")
    parser.add_argument("--topic",  default="events-envelope",  help="Target topic")
    parser.add_argument("--count",  type=int, default=10,        help="Messages per type")
    parser.add_argument("--delay",  type=float, default=0.2,     help="Seconds between rounds")
    args = parser.parse_args()

    producer = Producer({"bootstrap.servers": args.broker, "linger.ms": 5})

    def on_delivery(err, msg):
        if err:
            print(f"  [ERROR] delivery failed: {err}")
        else:
            print(f"  [OK]    {msg.topic()} [{msg.partition()}] offset={msg.offset()}")

    total = 0
    print(f"Producing {args.count} messages per type to '{args.topic}'...")
    for _ in range(args.count):
        for gen in GENERATORS:
            ev = gen()
            print(f"  [{ev.event_type}]  {str(ev).strip().replace(chr(10), ' ')}")
            producer.produce(topic=args.topic, value=ev.SerializeToString(), callback=on_delivery)
            producer.poll(0)
            total += 1
        if args.delay > 0:
            time.sleep(args.delay)

    producer.flush()
    print(f"\nDone. Produced {total} messages total.")


if __name__ == "__main__":
    main()
