apiVersion: v1
kind: Namespace
metadata:
  name: timeplus
  labels:
    name: timeplus

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: timeplusd
  namespace: timeplus
  labels:
    app: timeplusd

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: timeplusd
  namespace: timeplus
  labels:
    app: timeplusd
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: timeplusd
  namespace: timeplus
  labels:
    app: timeplusd
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: timeplusd
subjects:
- kind: ServiceAccount
  name: timeplusd
  namespace: timeplus 

---

apiVersion: v1
kind: Service
metadata:
  name: timeplusd-public
  namespace: timeplus
  labels:
    app: timeplusd
spec:
  ports:
  - port: 8463
    targetPort: 8463
    protocol: TCP
    name: native 
  - port: 8123 
    targetPort: 8123
    name: http
  selector:
    app: timeplusd
  type: LoadBalancer

---

apiVersion: v1
kind: Service
metadata:
  name: timeplusd
  namespace: timeplus
  labels:
    app: timeplusd
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
spec:
  ports:
  - port: 26257
    targetPort: 26257
    name: grpc
  - port: 8080
    targetPort: 8080
    name: http
  publishNotReadyAddresses: true
  clusterIP: None
  selector:
    app: timeplusd

---

apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: timeplusd-budget
  namespace: timeplus
  labels:
    app: timeplusd
spec:
  selector:
    matchLabels:
      app: timeplusd
  maxUnavailable: 1
