services:
  t1:
    image: timeplus/timeplusd:2.8.8
    container_name: timeplusd-meta-1
    ports:
     - "3218:3218" # HTTP Streaming
     - "8123:8123" # HTTP Snapshot
     - "8463:8463" # TCP Streaming
     - "5432:5432" # Postgres Snapshot
     - "7587:7587" # TCP Snapshot
     - "9444:9444" # kv service 
    entrypoint:
      - /bin/bash
      - -c
      - |
        # Fix user access network
        sed -i'' 's#::1#::/0#g' /etc/timeplusd-server/users.yaml
        sed -i'' 's/- ip: 127.0.0.1//g' /etc/timeplusd-server/users.yaml 

        # Enable kv_service
        sed -i'' '/^kv_service:/{N;s/\n\(.\+\)false/\n\1true/}' /etc/timeplusd-server/config.yaml

        # Fix others
        sed -i'' 's/\bcount: 10\b/count: 100/g' /etc/timeplusd-server/config.yaml 
        sed -i'' 's/preallocate: true/preallocate: false/g' /etc/timeplusd-server/config.yaml 
        
        # Launch timeplusd 
        /entrypoint.sh

    environment:
      - MAX_CONCURRENT_QUERIES=1000        # Default: 100
      - MAX_CONCURRENT_SELECT_QUERIES=1000     # Default: 100
      - MAX_CONCURRENT_INSERT_QUERIES=1000     # Default: 100
      - MAX_CONCURRENT_STREAMING_QUERIES=1000   # Default: 100
      - MAX_SERVER_MEMORY_USAGE_TO_RAM_RATIO=0.3 # Default: 0.9
      - MAX_SERVER_MEMORY_CACHE_TO_RAM_RATIO=0.2 # Default: 0.5
      - ADVERTISED_HOST=timeplusd-meta-1
      - METADATA_NODE_QUORUM="timeplusd-meta-1:8464,timeplusd-meta-2:8464,timeplusd-meta-3:8464"
    deploy:
      resources:
        limits:
          cpus: "4.0"   # Limit to 4 CPU cores
          memory: "5g"  # Limit memory to 8 GB
        reservations:
          cpus: "1.0"   # Reserve 1 CPU core
          memory: "2g"  # Reserve 2 GB of memory
    volumes:
      - /tmp/dump:/coredumps
      - timeplusd_data_1:/var/lib
    ulimits:
      core: -1
    cap_add:
      - SYS_PTRACE

  t2:
    image: timeplus/timeplusd:2.8.8
    container_name: timeplusd-meta-2
    ports:
     - "18463:8463"
     - "13218:3218"
    entrypoint:
      - /bin/bash
      - -c
      - |
        # Fix user access network
        sed -i'' 's#::1#::/0#g' /etc/timeplusd-server/users.yaml
        sed -i'' 's/- ip: 127.0.0.1//g' /etc/timeplusd-server/users.yaml 

        # Enable kv_service
        sed -i'' '/^kv_service:/{N;s/\n\(.\+\)false/\n\1true/}' /etc/timeplusd-server/config.yaml

        # Fix node id for kv_service
        sed -i'' 's/id: 1/id: 2/g' /etc/timeplusd-server/config.yaml 

        # Fix others
        sed -i'' 's/\bcount: 10\b/count: 100/g' /etc/timeplusd-server/config.yaml 
        sed -i'' 's/preallocate: true/preallocate: false/g' /etc/timeplusd-server/config.yaml 
        
        # Launch timeplusd 
        /entrypoint.sh

    environment:
      - MAX_CONCURRENT_QUERIES=1000        # Default: 100
      - MAX_CONCURRENT_SELECT_QUERIES=1000     # Default: 100
      - MAX_CONCURRENT_INSERT_QUERIES=1000     # Default: 100
      - MAX_CONCURRENT_STREAMING_QUERIES=1000   # Default: 100
      - MAX_SERVER_MEMORY_USAGE_TO_RAM_RATIO=0.3 # Default: 0.9
      - MAX_SERVER_MEMORY_CACHE_TO_RAM_RATIO=0.2 # Default: 0.5
      - ADVERTISED_HOST=timeplusd-meta-2
      - METADATA_NODE_QUORUM="timeplusd-meta-1:8464,timeplusd-meta-2:8464,timeplusd-meta-3:8464"
    deploy:
      resources:
        limits:
          cpus: "4.0"   # Limit to 4 CPU cores
          memory: "5g"  # Limit memory to 8 GB
        reservations:
          cpus: "1.0"   # Reserve 1 CPU core
          memory: "2g"  # Reserve 2 GB of memory
    volumes:
      - /tmp/dump:/coredumps
      - timeplusd_data_2:/var/lib
    ulimits:
      core: -1

  t3:
    image: timeplus/timeplusd:2.8.8
    container_name: timeplusd-meta-3
    ports:
     - "28463:8463"
     - "23218:3218"
    entrypoint:
      - /bin/bash
      - -c
      - |
        # Fix user access network
        sed -i'' 's#::1#::/0#g' /etc/timeplusd-server/users.yaml
        sed -i'' 's/- ip: 127.0.0.1//g' /etc/timeplusd-server/users.yaml 

        # Enable kv_service
        sed -i'' '/^kv_service:/{N;s/\n\(.\+\)false/\n\1true/}' /etc/timeplusd-server/config.yaml

        # Fix node id for kv_service
        sed -i'' 's/id: 1/id: 3/g' /etc/timeplusd-server/config.yaml 

        # Fix others
        sed -i'' 's/\bcount: 10\b/count: 100/g' /etc/timeplusd-server/config.yaml 
        sed -i'' 's/preallocate: true/preallocate: false/g' /etc/timeplusd-server/config.yaml 
        
        # Launch timeplusd 
        /entrypoint.sh

    environment:
      - MAX_CONCURRENT_QUERIES=1000        # Default: 100
      - MAX_CONCURRENT_SELECT_QUERIES=1000     # Default: 100
      - MAX_CONCURRENT_INSERT_QUERIES=1000     # Default: 100
      - MAX_CONCURRENT_STREAMING_QUERIES=1000   # Default: 100
      - MAX_SERVER_MEMORY_USAGE_TO_RAM_RATIO=0.3 # Default: 0.9
      - MAX_SERVER_MEMORY_CACHE_TO_RAM_RATIO=0.2 # Default: 0.5
      - ADVERTISED_HOST=timeplusd-meta-3
      - METADATA_NODE_QUORUM="timeplusd-meta-1:8464,timeplusd-meta-2:8464,timeplusd-meta-3:8464"
    deploy:
      resources:
        limits:
          cpus: "4.0"   # Limit to 4 CPU cores
          memory: "5g"  # Limit memory to 8 GB
        reservations:
          cpus: "1.0"   # Reserve 1 CPU core
          memory: "2g"  # Reserve 2 GB of memory
    volumes:
      - /tmp/dump:/coredumps
      - timeplusd_data_3:/var/lib
    ulimits:
      core: -1
  p1:
    image: timeplus/timeplusd:2.8.8
    container_name: timeplusd-compute-1
    ports:
     - "38463:8463" # TCP Streaming
    entrypoint: >
      /bin/bash -c "sed -i'' 's/\- Data/\- Compute/g' /etc/timeplusd-server/config.yaml && sed -i'' 's/\- Metadata//g' /etc/timeplusd-server/config.yaml && sed -i'' 's/\bcount: 10\b/count: 100/g' /etc/timeplusd-server/config.yaml && sed -i'' 's/preallocate: true/preallocate: false/g' /etc/timeplusd-server/config.yaml && /entrypoint.sh"
    environment:
      - MAX_CONCURRENT_QUERIES=1000        # Default: 100
      - MAX_CONCURRENT_SELECT_QUERIES=1000     # Default: 100
      - MAX_CONCURRENT_INSERT_QUERIES=1000     # Default: 100
      - MAX_CONCURRENT_STREAMING_QUERIES=1000   # Default: 100
      - MAX_SERVER_MEMORY_USAGE_TO_RAM_RATIO=0.3 # Default: 0.9
      - MAX_SERVER_MEMORY_CACHE_TO_RAM_RATIO=0.2 # Default: 0.5
      - ADVERTISED_HOST=timeplusd-compute-1
      - METADATA_NODE_QUORUM="timeplusd-meta-1:8464,timeplusd-meta-2:8464,timeplusd-meta-3:8464"
    deploy:
      resources:
        limits:
          cpus: "4.0"   # Limit to 4 CPU cores
          memory: "5g"  # Limit memory to 8 GB
        reservations:
          cpus: "1.0"   # Reserve 1 CPU core
          memory: "2g"  # Reserve 2 GB of memory
    volumes:
      - /tmp/dump:/coredumps
      - timeplusd_data_11:/var/lib
    ulimits:
      core: -1
  p2:
    image: timeplus/timeplusd:2.8.8
    container_name: timeplusd-compute-2
    ports:
     - "48463:8463" # TCP Streaming
    entrypoint: >
      /bin/bash -c "sed -i'' 's/\- Data/\- Compute/g' /etc/timeplusd-server/config.yaml && sed -i'' 's/\- Metadata//g' /etc/timeplusd-server/config.yaml && sed -i'' 's/\bcount: 10\b/count: 100/g' /etc/timeplusd-server/config.yaml && sed -i'' 's/preallocate: true/preallocate: false/g' /etc/timeplusd-server/config.yaml && /entrypoint.sh"
    environment:
      - MAX_CONCURRENT_QUERIES=1000        # Default: 100
      - MAX_CONCURRENT_SELECT_QUERIES=1000     # Default: 100
      - MAX_CONCURRENT_INSERT_QUERIES=1000     # Default: 100
      - MAX_CONCURRENT_STREAMING_QUERIES=1000   # Default: 100
      - MAX_SERVER_MEMORY_USAGE_TO_RAM_RATIO=0.3 # Default: 0.9
      - MAX_SERVER_MEMORY_CACHE_TO_RAM_RATIO=0.2 # Default: 0.5
      - ADVERTISED_HOST=timeplusd-compute-2
      - METADATA_NODE_QUORUM="timeplusd-meta-1:8464,timeplusd-meta-2:8464,timeplusd-meta-3:8464"
    deploy:
      resources:
        limits:
          cpus: "4.0"   # Limit to 4 CPU cores
          memory: "4g"  # Limit memory to 8 GB
        reservations:
          cpus: "1.0"   # Reserve 1 CPU core
          memory: "2g"  # Reserve 2 GB of memory
    volumes:
      - /tmp/dump:/coredumps
      - timeplusd_data_22:/var/lib
    ulimits:
      core: -1
  p3:
    image: timeplus/timeplusd:2.8.8
    container_name: timeplusd-data-1
    ports:
      - "58483:8463" # TCP Streaming
    entrypoint: >
      /bin/bash -c "sed -i'' 's/\- Metadata//g' /etc/timeplusd-server/config.yaml && sed -i'' 's/\bcount: 10\b/count: 100/g' /etc/timeplusd-server/config.yaml && sed -i'' 's/preallocate: true/preallocate: false/g' /etc/timeplusd-server/config.yaml && /entrypoint.sh"
    environment:
      - MAX_CONCURRENT_QUERIES=1000        # Default: 100
      - MAX_CONCURRENT_SELECT_QUERIES=1000     # Default: 100
      - MAX_CONCURRENT_INSERT_QUERIES=1000     # Default: 100
      - MAX_CONCURRENT_STREAMING_QUERIES=1000   # Default: 100
      - MAX_SERVER_MEMORY_USAGE_TO_RAM_RATIO=0.3 # Default: 0.9
      - MAX_SERVER_MEMORY_CACHE_TO_RAM_RATIO=0.2 # Default: 0.5
      - ADVERTISED_HOST=timeplusd-data-1
      - METADATA_NODE_QUORUM="timeplusd-meta-1:8464,timeplusd-meta-2:8464,timeplusd-meta-3:8464"
    deploy:
      resources:
        limits:
          cpus: "4.0"   # Limit to 4 CPU cores
          memory: "6g"  # Limit memory to 8 GB
        reservations:
          cpus: "1.0"   # Reserve 1 CPU core
          memory: "2g"  # Reserve 2 GB of memory
    volumes:
      - /tmp/dump:/coredumps
      - timeplusd_data_33:/var/lib
    ulimits:
      core: -1

volumes:
  timeplusd_data_1:
    driver: local
  timeplusd_data_2:
    driver: local
  timeplusd_data_3:
    driver: local
  timeplusd_data_11:
    driver: local
  timeplusd_data_22:
    driver: local
  timeplusd_data_33:
    driver: local
