#!/usr/bin/env python3
"""
produce.py — produce mixed Protobuf messages to a single Kafka topic.

Serializes records in Confluent Protobuf wire format (magic byte + schema id +
message-index + payload) using the schemas registered by setup.sh, then
publishes them to the configured topic. The fan-out recipe consumes this topic,
decodes each message, and routes it to one of three Timeplus streams.

Usage:
  pip install confluent-kafka protobuf grpcio-tools
  ./setup.sh                      # generates *_pb2.py and registers schemas
  python produce.py [--broker localhost:9092] [--registry http://localhost:8081]
                    [--topic mixed-events] [--count 10]
"""

import argparse
import random
import time
import uuid

from confluent_kafka import Producer
from confluent_kafka.schema_registry import (
    SchemaRegistryClient,
    record_subject_name_strategy,
)
from confluent_kafka.schema_registry.protobuf import ProtobufSerializer
from confluent_kafka.serialization import MessageField, SerializationContext

# Generated by setup.sh (python -m grpc_tools.protoc ...)
import order_pb2
import device_pb2
import click_pb2


# ---------------------------------------------------------------------------
# Sample record generators (exercise the recipe's transform/if-else logic)
# ---------------------------------------------------------------------------

def _random_order() -> order_pb2.OrderEvent:
    return order_pb2.OrderEvent(
        order_id    = str(uuid.uuid4()),
        amount      = round(random.uniform(1.0, 999.99), 2),  # > 500 => tier "hot"
        customer_id = f"cust-{random.randint(1000, 9999)}",
    )


def _random_device() -> device_pb2.DeviceEvent:
    return device_pb2.DeviceEvent(
        device_id   = f"dev-{random.randint(1, 50):03d}",
        temperature = round(random.uniform(20.0, 100.0), 1),  # > 80 => status "alert"
        ts_ms       = int(time.time() * 1000),
    )


def _random_click() -> click_pb2.ClickEvent:
    # ~1 in 4 is a bot => dropped by the recipe transform.
    agents = ["Mozilla/5.0", "Safari/17.0", "Chrome/124.0", "Googlebot/2.1 (+http://www.google.com/bot.html)"]
    return click_pb2.ClickEvent(
        session_id = str(uuid.uuid4()),
        url        = random.choice(["/home", "/cart", "/checkout", "/product/42"]),
        user_agent = random.choice(agents),
        ts_ms      = int(time.time() * 1000),
    )


# subject -> (message generator, message type)
TYPES = [
    ("com.example.OrderEvent",  _random_order,  order_pb2.OrderEvent),
    ("com.example.DeviceEvent", _random_device, device_pb2.DeviceEvent),
    ("com.example.ClickEvent",  _random_click,  click_pb2.ClickEvent),
]


def main():
    parser = argparse.ArgumentParser(description="Produce mixed Protobuf messages to Kafka")
    parser.add_argument("--broker",   default="localhost:9092",        help="Kafka broker")
    parser.add_argument("--registry", default="http://localhost:8081", help="Schema Registry URL")
    parser.add_argument("--topic",    default="mixed-events",          help="Target topic")
    parser.add_argument("--count",    type=int, default=10,            help="Messages per type")
    parser.add_argument("--delay",    type=float, default=0.2,         help="Seconds between rounds")
    args = parser.parse_args()

    sr_client = SchemaRegistryClient({"url": args.registry})

    # Use the schemas already registered by setup.sh (do not auto-register), and
    # RecordNameStrategy so each message type maps to its own subject.
    ser_conf = {
        "auto.register.schemas": False,
        "use.latest.version": True,
        "use.deprecated.format": False,
        "subject.name.strategy": record_subject_name_strategy,
    }

    serializers = {
        subject: ProtobufSerializer(msg_type, sr_client, ser_conf)
        for subject, _gen, msg_type in TYPES
    }

    producer = Producer({"bootstrap.servers": args.broker, "linger.ms": 5})

    def on_delivery(err, msg):
        if err:
            print(f"  [ERROR] delivery failed: {err}")
        else:
            print(f"  [OK]    {msg.topic()} [{msg.partition()}] offset={msg.offset()}")

    ctx = SerializationContext(args.topic, MessageField.VALUE)

    total = 0
    print(f"Producing {args.count} messages per type to '{args.topic}'...")
    for _ in range(args.count):
        for subject, gen, _msg_type in TYPES:
            record  = gen()
            payload = serializers[subject](record, ctx)
            print(f"  [{subject}]  {str(record).strip().replace(chr(10), ' ')}")
            producer.produce(topic=args.topic, value=payload, callback=on_delivery)
            producer.poll(0)
            total += 1
        if args.delay > 0:
            time.sleep(args.delay)

    producer.flush()
    print(f"\nDone. Produced {total} messages total.")


if __name__ == "__main__":
    main()
