apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: bandwidth
spec:
  action: bandwidth
  mode: all
  selector:
      namespaces:
        - timeplus
      labelSelectors:
        app.kubernetes.io/component: timeplusd
        app.kubernetes.io/instance: timeplus
        app.kubernetes.io/name: timeplus-enterprise
  bandwidth:
    rate: 1mbps
    limit: 100000
    buffer: 100000