kind: NetworkChaos
apiVersion: chaos-mesh.org/v1alpha1
metadata:
 name: network-corruption
spec:
 selector:
  namespaces:
    - timeplus
  labelSelectors:
    app.kubernetes.io/component: timeplusd
    app.kubernetes.io/instance: timeplus
    app.kubernetes.io/name: timeplus-enterprise
 mode: one
 action: corrupt
 corrupt:
   corrupt: '15'
 direction: to