apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: delay
spec:
  action: delay
  mode: one
  selector:
    namespaces:
      - timeplus
    labelSelectors:
      app.kubernetes.io/component: timeplusd
      app.kubernetes.io/instance: timeplus
      app.kubernetes.io/name: timeplus-enterprise
  delay:
    latency: 10ms
    jitter: 100ms
