apiVersion: chaos-mesh.org/v1alpha1
kind: Schedule
metadata:
  name: schedule-pod-kill
spec:
  schedule: '*/1 * * * *'
  type: PodChaos
  concurrencyPolicy: 'Allow'
  podChaos:
    action: pod-kill
    mode: one
    duration: 30s
    selector:
      namespaces:
        - timeplus
      labelSelectors:
        app.kubernetes.io/component: timeplusd
        app.kubernetes.io/instance: timeplus
        app.kubernetes.io/name: timeplus-enterprise
