apiVersion: chaos-mesh.org/v1alpha1
kind: TimeChaos
metadata:
  name: time-shift
  namespace: chaos-mesh
spec:
  mode: one
  selector:
    namespaces:
      - timeplus
    labelSelectors:
      app.kubernetes.io/component: timeplusd
      app.kubernetes.io/instance: timeplus
      app.kubernetes.io/name: timeplus-enterprise
  timeOffset: -10m
  containerNames: [timeplusd]
  clockIds: ["CLOCK_REALTIME", "CLOCK_MONOTONIC"]
  